# Uncomment this line to define a global platform for your project
ali_source 'alibaba-specs'
ali_source 'alibaba-specs-mirror'
# source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'
inhibit_all_warnings!
target 'TBWXDevTool' do
	pod 'WeexSDK', '~> 0.7.0.14'
end
