source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
#inhibit_all_warnings!

def common
    pod 'WeexSDK','0.8.0'
    pod 'WXDevtool', :path=>'../WXDevtool/'
    pod 'SDWebImage', '3.7.5'
    pod 'SocketRocket', '0.4.2'
    pod 'ATSDK-Weex'
end

target 'WeexDemo' do
    common
end

target 'WeexUITestDemo' do
    common
end
