# Uncomment this line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

inhibit_all_warnings!
use_frameworks!

def pods 

  pod 'ZPMWeexSDK','0.28.0'
  pod 'SocketRocket', '0.4.2'

end

target 'WXDevTool' do
	pods
end
