# Uncomment this line to define a global platform for your project
source 'git@github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

inhibit_all_warnings!

target 'WXDevTool' do
	pod 'WeexSDK'
  pod 'SocketRocket'
end
